import { APP_CONFIG } from './config.js';
import { $,brand,icon,toast } from './common.js';
const sessionKey='sa3AdminSession';
export function requireAdmin(){try{if(JSON.parse(sessionStorage.getItem(sessionKey))?.loggedIn===true)return true;}catch{}location.replace('login.html');return false;}
export function adminShell(active,title){if(!requireAdmin())return false;
 document.body.innerHTML=`<a class="skip-link" href="#main-content">Lewati ke konten</a><aside class="admin-sidebar" id="admin-sidebar">${brand('../')}<span class="sidebar-label">WORKSPACE</span><nav class="admin-nav" aria-label="Navigasi admin">${[['dashboard','grid','Dashboard'],['patients','people','Assessment / Pasien']].map(([path,i,t])=>`<a class="${active===path?'active':''}" href="${path}.html" ${active===path?'aria-current="page"':''}>${icon(i)}${t}</a>`).join('')}<span class="sidebar-label">PENGELOLAAN</span><a class="${active==='settings'?'active':''}" href="settings.html">${icon('settings')}Pengaturan</a><a href="../index.html">${icon('home')}Buka Website ${icon('arrow')}</a></nav><div class="sidebar-bottom"><div class="prototype-label"><span></span> Mode: Local Prototype</div><nav class="admin-nav"><button id="logout">${icon('logout')}Keluar</button></nav></div></aside><button class="drawer-backdrop" id="drawer-backdrop" aria-label="Tutup menu admin" tabindex="-1"></button><div class="admin-body"><header class="admin-topbar"><button class="icon-button menu-toggle" id="admin-menu" aria-label="Buka menu admin" aria-expanded="false" aria-controls="admin-sidebar">${icon('menu')}</button><div class="admin-breadcrumb">Workspace <span> / </span><strong>${title}</strong></div><div class="admin-user"><span class="avatar">SA</span><div><strong>Admin SA3</strong><small>Administrator</small></div></div></header><main class="admin-main" id="main-content"><div class="loading-state">Memuat data…</div></main></div><div id="toast" class="hidden" role="status" aria-live="polite"></div>`;
 $('#logout').addEventListener('click',()=>{sessionStorage.removeItem(sessionKey);location.href='login.html';});const menu=$('#admin-menu'),sidebar=$('#admin-sidebar'),backdrop=$('#drawer-backdrop');
 const setOpen=open=>{menu.setAttribute('aria-expanded',String(open));sidebar.classList.toggle('is-open',open);backdrop.classList.toggle('is-open',open);document.body.classList.toggle('drawer-open',open);if(open)sidebar.querySelector('a').focus();};
 menu.addEventListener('click',()=>setOpen(menu.getAttribute('aria-expanded')!=='true'));backdrop.addEventListener('click',()=>{setOpen(false);menu.focus();});document.addEventListener('keydown',e=>{if(menu.getAttribute('aria-expanded')!=='true')return;if(e.key==='Escape'){setOpen(false);menu.focus();}if(e.key==='Tab'){const all=[...sidebar.querySelectorAll('a,button')];if(e.shiftKey&&document.activeElement===all[0]){e.preventDefault();all.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===all.at(-1)){e.preventDefault();all[0].focus();}}});return true;
}
if(document.body.dataset.page==='login'){
 document.body.innerHTML=`<main class="login-page"><section class="login-visual">${brand('../')}<div><span class="eyebrow" style="color:#d6ecd8">SA3 HOME CARE · ADMIN WORKSPACE</span><h1>Di balik perawatan yang baik,<br>ada tim yang <em style="color:#cde7ce">peduli.</em></h1><p>Kelola kebutuhan keluarga dan tindak lanjut layanan dalam satu tempat.</p></div><small>Silih Asih · Silih Asah · Silih Asuh</small></section><section class="login-content"><span class="tag">Prototype Lokal</span><h2>Selamat datang kembali.</h2><p>Masuk untuk mengelola assessment kebutuhan pasien.</p><form id="login-form"><label class="form-field">Username<input name="username" autocomplete="username" required placeholder="Username admin"></label><label class="form-field">Password<input name="password" type="password" autocomplete="current-password" required placeholder="Masukkan password"></label><p class="form-error" id="login-error" role="alert"></p><button class="btn" type="submit">Masuk ke Dashboard ${icon('arrow')}</button></form><div class="login-demo">Akun demo: <code>admin</code> / <code>sa3demo2026</code><br>Login ini hanya gerbang demo, bukan autentikasi aman untuk operasional.</div><a class="text-link" href="../index.html">← Kembali ke website</a></section></main>`;
 $('#login-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);if(data.get('username')===APP_CONFIG.admin.username&&data.get('password')===APP_CONFIG.admin.password){try{sessionStorage.setItem(sessionKey,JSON.stringify({loggedIn:true,loginAt:new Date().toISOString()}));location.href='dashboard.html';}catch{toast('Izinkan penyimpanan sesi browser untuk masuk.',true);}}else{$('#login-error').textContent='Username atau password tidak sesuai.';e.target.elements.password.focus();}});
}
