import './public.js';
import { $,icon,esc,validPhone,normalizePhone,localDay,toast } from './common.js';
import { createAssessment,getAssessment } from './db.js';
import { SERVICES } from './config.js';
import { STEPS,summaryMarkup } from './assessment-schema.js';
const draftKey='sa3AssessmentDraft';
let current=0,busy=false;
let draft=Object.fromEntries(STEPS.map(s=>[s.group,Object.fromEntries(s.fields.map(f=>[f.key,f.type==='checks'?[]:'']))]));
try{const stored=JSON.parse(sessionStorage.getItem(draftKey));if(stored?.draft){for(const step of STEPS)for(const f of step.fields){const value=stored.draft[step.group]?.[f.key];if(f.type==='checks'?Array.isArray(value):typeof value==='string')draft[step.group][f.key]=value;}draft.consent=stored.draft.consent||{};current=Math.min(5,Math.max(0,Number(stored.current)||0));}}catch{sessionStorage.removeItem(draftKey);}
const preselect=new URLSearchParams(location.search).get('service');if(!draft.service.primary&&SERVICES.some(s=>s.id===preselect))draft.service.primary=preselect;
const main=$('#main-content');
main.innerHTML=`<div class="assessment-intro container"><span class="eyebrow">LANGKAH PERTAMA BERSAMA SA3</span><h1>Mari pahami <em>kebutuhan Anda.</em></h1><p>Isi informasi awal untuk membantu kami menyiapkan pendampingan yang sesuai.</p></div><div class="assessment-container"><div class="callout">${icon('medical')}<span>Jika kondisi pasien darurat atau memburuk cepat, jangan menunggu respons dari form ini. Segera hubungi layanan darurat atau fasilitas kesehatan terdekat.</span></div><div class="assessment-layout"><aside class="wizard-sidebar"><h2>Kebutuhan perawatan</h2><ol class="wizard-steps" id="wizard-steps"></ol><div class="wizard-help"><p>Belum yakin harus mengisi apa? Tim kami siap membantu.</p><a href="/kontak">${icon('chat')} Hubungi tim SA3</a></div></aside><div><form id="assessment-form" class="form-card" novalidate><div class="form-heading"><span id="step-label"></span><span>± 5–8 menit</span></div><div class="progress-track"><span id="progress"></span></div><div id="step-content"></div><p class="form-error" id="form-error" role="alert"></p><div class="wizard-actions"><button type="button" class="btn btn-light" id="previous">← Kembali</button><button type="submit" class="btn" id="next">Lanjutkan ${icon('arrow')}</button></div></form><p class="form-save-note">Draft tersimpan selama sesi tab ini. Gunakan data fiktif untuk demo lokal.</p></div></div></div>`;
const form=$('#assessment-form');
function saveDraft(){try{sessionStorage.setItem(draftKey,JSON.stringify({draft,current}));}catch{toast('Draft tidak dapat disimpan di sesi browser ini.',true);}}
function fieldMarkup(f,group){const name=`${group}.${f.key}`,id=`field-${group}-${f.key}`,value=draft[group][f.key];
 const options=(f.options||[]).map(o=>Array.isArray(o)?o:[o,o]);
 if(f.type==='checks')return `<fieldset class="choice-group ${f.full?'full-width':''}"><legend>${f.label}</legend><div class="choice-grid">${options.map(([v,l],i)=>`<label class="check-label" for="${id}-${i}"><input type="checkbox" id="${id}-${i}" name="${name}" value="${esc(v)}" ${value.includes(v)?'checked':''}>${esc(l)}</label>`).join('')}</div></fieldset>`;
 let input;
 const attrs=`id="${id}" name="${name}" ${f.required?'required':''} aria-describedby="${id}-error" ${f.autocomplete?`autocomplete="${f.autocomplete}"`:''}`;
 if(f.options)input=`<select ${attrs}><option value="">Pilih ${f.label.replace(' (opsional)','').toLowerCase()}</option>${options.map(([v,l])=>`<option value="${esc(v)}" ${value===v?'selected':''}>${esc(l)}</option>`).join('')}</select>`;
 else if(f.type==='textarea')input=`<textarea ${attrs} maxlength="2000" rows="3">${esc(value)}</textarea>`;
 else input=`<input ${attrs} type="${f.type||'text'}" value="${esc(value)}" ${f.type==='date'?`min="${localDay()}"`:''} ${f.type==='tel'?'inputmode="tel"':''} ${f.min?`minlength="${f.min}"`:''} ${f.placeholder?`placeholder="${esc(f.placeholder)}"`:''} ${!['date','tel','email'].includes(f.type)?'maxlength="200"':''}>`;
 return `<label class="form-field ${f.full?'full-width':''}" for="${id}">${f.label}${f.required?' *':''}${input}<span class="field-error" id="${id}-error"></span></label>`;
}
function render(){const step=STEPS[current];$('#wizard-steps').innerHTML=STEPS.map((s,i)=>`<li class="${i===current?'current':i<current?'done':''}" ${i===current?'aria-current="step"':''}><span>${i<current?'✓':i+1}</span>${s.short}</li>`).join('');$('#step-label').textContent=`LANGKAH ${current+1} DARI 6`;$('#progress').style.width=`${(current+1)/6*100}%`;$('#form-error').textContent='';
 $('#step-content').innerHTML=`<h2 tabindex="-1" id="step-title">${step.title}</h2><p class="form-description">${step.desc}</p>${current===5?`${summaryMarkup(draft)}<div class="consent-section"><label class="check-label"><input name="consent.initialAssessment" type="checkbox" required ${draft.consent.initialAssessment?'checked':''}>Saya memahami bahwa informasi ini merupakan assessment awal untuk membantu tim SA3 Home Care memahami kebutuhan layanan dan bukan diagnosis atau pengganti pemeriksaan tenaga kesehatan.</label><label class="check-label"><input name="consent.privacy" type="checkbox" required ${draft.consent.privacy?'checked':''}>Saya menyetujui penggunaan data yang saya kirim untuk keperluan konsultasi dan tindak lanjut layanan.</label><p class="small muted">Prototype: data tersimpan di browser perangkat ini. Tombol WhatsApp di halaman berikutnya akan membuka ringkasan untuk Anda kirim.</p></div>`:`<div class="grid-2">${step.fields.map(f=>fieldMarkup(f,step.group)).join('')}</div>`}`;
 $('#previous').hidden=current===0;$('#next').innerHTML=current===5?`Simpan Assessment ${icon('check')}`:`Lanjutkan ${icon('arrow')}`;saveDraft();
}
function capture(){for(const el of form.querySelectorAll('[name]')){const [group,key]=el.name.split('.');if(el.type==='checkbox'){if(group==='consent')draft[group][key]=el.checked;else draft[group][key]=[...form.querySelectorAll(`[name="${el.name}"]:checked`)].map(x=>x.value);}else draft[group][key]=el.value;}saveDraft();}
function validation(stepIndex){const errors=[];const step=STEPS[stepIndex];for(const f of step.fields){const value=draft[step.group][f.key];let message='';if(f.required&&!String(value).trim())message='Bagian ini wajib diisi.';else if(f.min&&value.trim().length<f.min)message=`Isi minimal ${f.min} karakter.`;else if(f.key==='whatsapp'&&!validPhone(value))message='Masukkan nomor Indonesia yang valid, diawali 08 atau +62 (minimal 9 digit).';else if(f.type==='email'&&value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))message='Alamat email belum valid.';else if(f.type==='date'&&value&&value<localDay())message='Pilih hari ini atau tanggal mendatang.';else if(f.options&&f.type!=='checks'&&value&&!f.options.some(o=>(Array.isArray(o)?o[0]:o)===value))message='Pilih opsi yang tersedia.';if(message)errors.push({name:`${step.group}.${f.key}`,message});}if(stepIndex===5){for(const key of ['initialAssessment','privacy'])if(!draft.consent[key])errors.push({name:`consent.${key}`,message:'Kedua persetujuan diperlukan sebelum melanjutkan.'});}return errors;}
function showErrors(errors){$('#form-error').textContent=errors.length?'Periksa isian yang ditandai sebelum melanjutkan.':'';for(const el of form.querySelectorAll('[aria-invalid]'))el.removeAttribute('aria-invalid');for(const el of form.querySelectorAll('.field-error'))el.textContent='';for(const {name,message} of errors){const el=form.elements.namedItem(name);if(el){el.setAttribute('aria-invalid','true');const error=$(`#${el.id}-error`);if(error)error.textContent=message;else $('#form-error').textContent=message;}}form.elements.namedItem(errors[0]?.name)?.focus();}
form.addEventListener('input',capture);form.addEventListener('change',capture);
$('#previous').addEventListener('click',()=>{capture();current--;render();$('#step-title').focus();});
form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;capture();const errors=validation(current);if(errors.length){showErrors(errors);return;}if(current<5){current++;render();$('#step-title').focus();return;}
 for(let i=0;i<5;i++){const errors=validation(i);if(errors.length){current=i;render();showErrors(errors);return;}}
 busy=true;$('#form-error').textContent='';$('#next').disabled=true;$('#previous').disabled=true;$('#next').textContent='Menyimpan…';
 try{let id;const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';do{const random=crypto.getRandomValues(new Uint8Array(4));id=`SA3-${localDay().replaceAll('-','')}-${[...random].map(n=>alphabet[n%alphabet.length]).join('')}`;}while(await getAssessment(id));
 const now=new Date().toISOString();const a={...structuredClone(draft),id,createdAt:now,updatedAt:now,status:'Baru',admin:{note:''}};a.contact.whatsapp=normalizePhone(a.contact.whatsapp);a.contact.name=a.contact.name.trim();a.patient.name=a.patient.name.trim();a.patient.city=a.patient.city.trim();await createAssessment(a);sessionStorage.removeItem(draftKey);location.href=`/assessment-success?id=${encodeURIComponent(id)}`;
 }catch{busy=false;$('#next').disabled=false;$('#previous').disabled=false;$('#next').textContent='Coba simpan kembali';$('#form-error').textContent='Assessment belum tersimpan. Periksa izin penyimpanan browser dan coba lagi. Draft Anda masih tersedia.';}
});
render();
