import './public.js';
import { $,icon,esc,buildWhatsAppMessage,buildWhatsAppUrl,adminNumber,copyText,errorState } from './common.js';
import { getAssessment,addActivityLog } from './db.js';
import { summaryMarkup } from './assessment-schema.js';
async function init(){const main=$('#main-content');try{const id=new URLSearchParams(location.search).get('id');const a=id?await getAssessment(id):null;if(!a){main.innerHTML=`<div class="success-container empty-state">${icon('search')}<h1>Assessment tidak ditemukan</h1><p>Gunakan browser dan alamat localhost yang sama dengan saat mengisi assessment.</p><a class="btn" href="/assessment">Isi Assessment Baru</a></div>`;return;}
 const message=buildWhatsAppMessage(a);main.innerHTML=`<div class="success-container"><div class="success-header"><div class="success-icon">${icon('check')}</div><span class="eyebrow">LANGKAH PERTAMA SELESAI</span><h1>Terima kasih sudah <em>bercerita.</em></h1><p>Assessment Anda tersimpan di browser ini. Lanjutkan dengan mengirim ringkasan ke WhatsApp agar tim SA3 dapat menindaklanjuti.</p><span class="tag">${esc(a.id)}</span> <button class="icon-button" id="copy-id" aria-label="Salin ID assessment">${icon('copy')}</button></div><div class="card">${summaryMarkup(a)}</div><div class="success-actions"><a class="btn" id="send-whatsapp" target="_blank" rel="noopener" href="${esc(buildWhatsAppUrl(await adminNumber(),message))}">${icon('whatsapp','on-dark')} Kirim Hasil Assessment ke WhatsApp ${icon('arrow')}</a><button class="btn btn-light" id="copy-summary">${icon('copy')} Copy Ringkasan</button><p>WhatsApp akan terbuka dengan pesan siap kirim. Pesan belum terkirim sampai Anda menekan Kirim di WhatsApp.</p><a class="text-link" href="/" style="justify-content:center">Kembali ke Beranda ${icon('arrow')}</a></div><details><summary>Lihat teks ringkasan WhatsApp</summary><pre class="summary-raw">${esc(message)}</pre></details></div>`;
 $('#copy-summary').addEventListener('click',()=>copyText(message));$('#copy-id').addEventListener('click',()=>copyText(a.id));$('#send-whatsapp').addEventListener('click',()=>addActivityLog({assessmentId:a.id,type:'whatsapp_clicked',message:'Tombol ringkasan WhatsApp dibuka'}).catch(()=>{}));
 }catch{errorState(main);}}
init();
