import { $,icon,brand,esc,buildWhatsAppUrl,adminNumber } from './common.js';
import { APP_CONFIG,SERVICES } from './config.js';
const page=document.body.dataset.page;
const wa=buildWhatsAppUrl(APP_CONFIG.whatsappNumber,'Halo SA3 Home Care, saya ingin berkonsultasi mengenai layanan home care.');
const links=[['index','Beranda'],['tentang','Tentang Kami'],['layanan','Layanan'],['blog','Artikel'],['kontak','Kontak']];
$('#site-header').innerHTML=`<div class="top-strip"><div class="container"><span>Kami Ada Sepenuh Hati Untuk Anda</span><span>Berpusat di Bandung · Melayani dengan hati sejak 2016 <a href="mailto:homecaresa3@gmail.com">homecaresa3@gmail.com</a></span></div></div><header class="site-header"><div class="container navbar">${brand()}<nav class="nav-links" id="public-nav" aria-label="Navigasi utama">${links.map(([href,name])=>`<a href="${href==='index'?'/':'/'+href}" class="${page===href?'active':''}" ${page===href?'aria-current="page"':''}>${name}</a>`).join('')}</nav><a class="nav-phone" data-wa href="${wa}" target="_blank" rel="noopener">${icon('whatsapp')}<span><small>KONSULTASI VIA WHATSAPP</small><strong>0823 1919 9534</strong></span></a><button class="icon-button menu-toggle" aria-label="Buka menu" aria-controls="public-nav" aria-expanded="false">${icon('menu')}</button></div></header>`;
$('#site-footer').innerHTML=`<section class="contact-band"><div class="container"><div><span class="eyebrow">MARI BICARA</span><h2>Perawatan terbaik dimulai<br>dari percakapan yang baik.</h2><p>Kami siap mendengarkan kebutuhan Anda dan keluarga.</p></div><a class="btn" data-wa href="${wa}" target="_blank" rel="noopener">${icon('whatsapp','on-dark')} Konsultasi via WhatsApp ${icon('arrow')}</a></div></section><footer class="footer"><div class="container"><div class="footer-grid"><div class="footer-brand">${brand()}<p>Perawatan profesional dengan kehangatan keluarga. Kami ada sepenuh hati untuk Anda.</p></div><div><h3>Jelajahi SA3</h3><a href="/tentang">Tentang Kami</a><a href="/layanan">Layanan Kami</a><a href="/blog">Artikel & Informasi</a><a href="/assessment">Assessment Kebutuhan</a></div><div><h3>Layanan Pilihan</h3><a href="/layanan#lansia">Pendampingan Lansia</a><a href="/layanan#stroke">Perawatan Pasien Stroke</a><a href="/layanan#visit">Visit Dokter & Perawat</a><a href="/layanan#fisio">Fisioterapi di Rumah</a></div><div><h3>Hubungi Kami</h3><p>Jl. Lodaya No.65, Malabar<br>Kota Bandung, Jawa Barat</p><a href="tel:+6282319199534">0823 1919 9534</a><a href="tel:+62895325404906">0895 3254 04906</a><a href="mailto:homecaresa3@gmail.com">homecaresa3@gmail.com</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} SA3 Home Care. Sepenuh hati untuk keluarga.</span><a href="/admin/login">Portal Admin ${icon('arrow')}</a></div></div></footer><a class="floating-wa" data-wa href="${wa}" target="_blank" rel="noopener" aria-label="Konsultasi via WhatsApp">${icon('whatsapp')}</a>`;
const toggle=$('.menu-toggle');
const drawer=document.createElement('dialog');
drawer.id='mobile-nav-dialog';
drawer.className='mobile-nav-dialog';
drawer.setAttribute('aria-label','Menu utama SA3 Home Care');
const navIcons=['home','heart','medical','copy','pin'];
drawer.innerHTML=`<div class="mobile-nav-head">${brand()}<button class="icon-button mobile-nav-close" aria-label="Tutup menu">${icon('close')}</button></div><div class="mobile-nav-intro"><span class="eyebrow">SELAMAT DATANG DI SA3</span><h2>Selalu dekat.<br><em>Sepenuh hati.</em></h2><p>Temukan pendampingan untuk keluarga Anda.</p></div><nav class="mobile-nav-links" aria-label="Menu mobile">${links.map(([href,name],i)=>`<a href="${href==='index'?'/':'/'+href}" ${page===href?'aria-current="page"':''}><span class="mobile-nav-icon">${icon(navIcons[i])}</span><span>${name}</span>${icon('arrow')}</a>`).join('')}</nav><div class="mobile-nav-bottom"><div class="mobile-nav-care"><span class="icon-box">${icon('heart')}</span><strong>Setiap keluarga berarti.</strong><p>Mari pahami kebutuhan perawatan Anda.</p><a class="btn" href="/assessment">Isi Assessment Kebutuhan ${icon('arrow')}</a></div><a class="mobile-nav-whatsapp" data-wa href="${wa}" target="_blank" rel="noopener">${icon('whatsapp')} Konsultasi via WhatsApp ${icon('arrow')}</a><small>Kami Ada Sepenuh Hati Untuk Anda</small></div>`;
document.body.append(drawer);
toggle.setAttribute('aria-controls',drawer.id);
toggle.setAttribute('aria-haspopup','dialog');
let closeTimer;
function closeMenu(immediate=false){
 clearTimeout(closeTimer);drawer.classList.remove('is-open');
 toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Buka menu');
 const finish=()=>{if(drawer.open)drawer.close();document.body.classList.remove('mobile-menu-open');};
 if(immediate||matchMedia('(prefers-reduced-motion: reduce)').matches)finish();else closeTimer=setTimeout(finish,300);
}
toggle.addEventListener('click',()=>{
 clearTimeout(closeTimer);
 if(drawer.open){closeMenu();return;}
 drawer.showModal();document.body.classList.add('mobile-menu-open');
 toggle.setAttribute('aria-expanded','true');toggle.setAttribute('aria-label','Tutup menu');
 requestAnimationFrame(()=>requestAnimationFrame(()=>{if(drawer.open)drawer.classList.add('is-open');}));
 $('.mobile-nav-close',drawer).focus();
});
$('.mobile-nav-close',drawer).addEventListener('click',()=>closeMenu());
drawer.addEventListener('cancel',e=>{e.preventDefault();closeMenu();});
drawer.addEventListener('keydown',e=>{
 if(e.key!=='Tab')return;
 const focusable=[...drawer.querySelectorAll('a[href],button:not(:disabled)')];
 const first=focusable[0],last=focusable.at(-1);
 if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}
 else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}
});
drawer.addEventListener('click',e=>{const rect=drawer.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right)closeMenu();if(e.target.closest('a'))closeMenu(true);});
drawer.addEventListener('close',()=>{document.body.classList.remove('mobile-menu-open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Buka menu');});
matchMedia('(min-width:1024px)').addEventListener('change',e=>{if(e.matches)closeMenu(true);});
const serviceCard=(s,i)=>`<article class="service-card" id="${s.id}" data-aos="fade-up" data-aos-delay="${i%3*50}"><div class="service-top"><div class="icon-box">${icon(s.icon)}</div><span class="service-no">${String(i+1).padStart(2,'0')}</span></div><h3>${s.name}</h3><p>${s.desc}</p><a class="text-link" href="/assessment?service=${s.id}">Konsultasikan kebutuhan ${icon('arrow')}</a></article>`;
const heading=(label,title,text='')=>`<div class="section-heading"><span class="eyebrow">${label}</span><h2>${title}</h2>${text?`<p>${text}</p>`:''}</div>`;
const cta=()=>`<div class="cta-banner"><div><span class="eyebrow">LANGKAH KECIL, KEPEDULIAN BESAR</span><h2>Setiap keluarga punya kebutuhan.<br>Mari temukan perawatan yang tepat.</h2><p>Ceritakan kondisi dan kebutuhan Anda melalui assessment awal.</p></div><a href="/assessment" class="btn btn-white">Isi Assessment Kebutuhan ${icon('arrow')}</a></div>`;
const about=()=>`<div class="about-grid"><div class="about-photo" data-aos="fade-up"><img src="/assets/images/hero.webp" alt="Perawat mendampingi lansia dengan penuh perhatian" width="600" height="440" loading="lazy"><div class="about-label"><strong>Sejak 2016</strong><small>Hadir untuk keluarga Indonesia</small></div></div><div class="about-copy"><span class="eyebrow">TENTANG SA3 HOME CARE</span><h2>Bukan sekadar merawat.<br>Kami hadir <em>sepenuh hati.</em></h2><p>Berawal di Bandung, SA3 Home Care mempertemukan keluarga dengan mitra dokter, perawat, dan tenaga kesehatan untuk perawatan di rumah.</p><p>Silih Asih, Silih Asah, Silih Asuh. Nilai inilah yang menghidupkan setiap pendampingan: saling mengasihi, berbagi pengetahuan, dan saling menjaga.</p><div class="values"><span>${icon('check')} Pelayanan penuh empati</span><span>${icon('check')} Tenaga profesional</span><span>${icon('check')} Kebutuhan yang personal</span><span>${icon('check')} Komunikasi terbuka</span></div><a class="text-link" href="/tentang">Kenali kami lebih dekat ${icon('arrow')}</a></div></div>`;
const articles=[
 {id:'persiapan',category:'PANDUAN KELUARGA',title:'Mempersiapkan rumah untuk layanan home care',desc:'Hal-hal sederhana untuk menyambut tenaga pendamping di rumah Anda.',image:'caregiver.webp',paragraphs:['Memulai layanan home care menjadi lebih mudah ketika keluarga dan penyedia layanan memiliki informasi yang sama. Tuliskan harapan keluarga, rutinitas pasien, serta pertanyaan yang ingin didiskusikan sebelum kunjungan pertama.','Siapkan informasi alamat dan akses masuk rumah. Beri tahu tim tentang tangga, lift, ketersediaan keluarga pendamping, serta bahasa komunikasi yang nyaman. Informasi ini membantu koordinasi kunjungan.','Sampaikan instruksi yang sudah diberikan oleh dokter atau tenaga kesehatan yang menangani pasien. Kebutuhan tindakan, alat, dan jadwal perawatan perlu dikonfirmasi bersama tenaga kesehatan, sesuai kondisi masing-masing pasien.','Anda dapat memulai dengan assessment kebutuhan SA3. Assessment ini merupakan pengumpulan informasi awal, bukan pemeriksaan atau diagnosis medis.']},
 {id:'pendamping',category:'PENDAMPINGAN LANSIA',title:'Menemukan pendamping yang tepat untuk orang tua',desc:'Mulai dari rutinitas, kebiasaan, dan kenyamanan orang tua tersayang.',image:'doctor.webp',paragraphs:['Setiap keluarga memiliki kebutuhan pendampingan yang berbeda. Ada yang membutuhkan teman aktivitas sehari-hari, ada pula yang memerlukan dukungan tenaga kesehatan sesuai arahan dokter.','Diskusikan bersama orang tua mengenai rutinitas dan preferensinya. Sampaikan kebutuhan bantuan makan, berpakaian, berjalan, atau komunikasi kepada penyedia layanan.','Tanyakan pembagian tugas pendamping, durasi layanan, mekanisme pergantian tenaga, dan cara keluarga menerima kabar. Pastikan kesepakatan layanan dipahami sebelum layanan dimulai.','Tim SA3 dapat membantu mendiskusikan kebutuhan pendampingan. Ketersediaan tenaga dan jadwal dikonfirmasi saat konsultasi.']},
 {id:'assessment',category:'MENGENAL HOME CARE',title:'Dari assessment hingga pendampingan di rumah',desc:'Kenali langkah awal untuk mendapatkan layanan bersama SA3 Home Care.',image:'therapy.webp',paragraphs:['Assessment awal membantu tim memahami informasi dasar pemesan, pasien, lokasi, serta layanan yang ingin didiskusikan. Anda tidak perlu mengetahui istilah medis untuk mengisinya.','Setelah mengisi, periksa kembali ringkasan kebutuhan. Anda dapat meneruskan ringkasan melalui tombol WhatsApp agar keluarga tidak perlu mengetik ulang informasi yang sama.','Tim akan mengonfirmasi kebutuhan, jangkauan area, ketersediaan tenaga, jadwal, dan biaya layanan. Mengirim assessment tidak otomatis mengonfirmasi pemesanan layanan.','Untuk kondisi darurat atau yang memburuk cepat, segera hubungi layanan darurat atau fasilitas kesehatan terdekat. Jangan menunggu balasan assessment.']}
];
const blogCards=()=>articles.map(a=>`<article class="blog-card" data-aos="fade-up"><img src="/assets/images/${a.image}" alt="Pendampingan dan perawatan di rumah" width="380" height="205" loading="lazy"><div class="blog-body"><div class="blog-meta"><span>${a.category}</span><span>3 MENIT BACA</span></div><h3>${a.title}</h3><p>${a.desc}</p><a class="text-link" href="/blog?artikel=${a.id}">Baca artikel ${icon('arrow')}</a></div></article>`).join('');
function home(){return `<div class="hero-wrap"><section class="hero"><img class="hero-image" src="/assets/images/caregiver.webp" width="1440" height="720" alt="Pendamping memberikan perhatian kepada lansia di rumah" fetchpriority="high"><div class="container"><div class="hero-content" data-aos="fade-up"><div class="hero-badge"><span></span> MITRA PERAWATAN KELUARGA SEJAK 2016</div><h1>Perawatan profesional,<br>hangat seperti<br><em>keluarga sendiri.</em></h1><p>Hadirkan perawatan yang tepat di tempat ternyaman. Dokter, perawat, dan pendamping untuk orang-orang yang paling berarti.</p><div class="actions"><a href="/assessment" class="btn btn-white">Isi Assessment Kebutuhan ${icon('arrow')}</a><a href="/layanan" class="btn btn-outline">Lihat Layanan ${icon('arrow')}</a></div><div class="hero-bottom">${icon('shield')}<div>Kami Ada Sepenuh Hati Untuk Anda<span>Respons cepat · Pendampingan personal · Tenaga profesional</span></div></div></div></div><div class="hero-note"><span class="icon-box">${icon('heart')}</span><div><strong>Lebih dekat. Lebih peduli.</strong><small>Perawatan dengan sentuhan hati.</small></div></div></section></div>
 <div class="container trust-strip">${[['shield','Berpengalaman','Melayani sejak 2016'],['clock','Respons Cepat','Kami siap mendengarkan'],['medical','Tenaga Profesional','Mitra dokter & perawat'],['pin','Jangkauan Luas','Hadir di berbagai wilayah']].map(([i,t,d])=>`<div class="trust-item">${icon(i)}<div><strong>${t}</strong><small>${d}</small></div></div>`).join('')}</div>
 <section class="section container">${heading('MENGAPA SA3 HOME CARE','Karena yang Anda sayangi<br>layak mendapat <em>yang terbaik.</em>','Perawatan yang memahami kebutuhan pasien dan menghadirkan ketenangan bagi seluruh keluarga.')}<div class="why-visual"><img src="/assets/images/doctor.webp" alt="Perawat dan lansia berinteraksi dengan hangat" width="1200" height="405" loading="lazy"><div class="why-cards">${[['heart','Personal, bukan sekadar prosedur','Pendampingan yang mengikuti kebutuhan, kebiasaan, dan kenyamanan pasien.'],['clock','Fleksibel mengikuti kebutuhan','Pilihan durasi dan jadwal yang didiskusikan bersama keluarga.'],['shield','Jelas sejak awal','Kebutuhan layanan dan biaya dikonfirmasi sebelum perawatan dimulai.']].map(([i,t,d])=>`<div class="card"><div class="icon-box">${icon(i)}</div><h3>${t}</h3><p>${d}</p></div>`).join('')}</div></div></section>
 <section class="section soft"><div class="container"><div class="section-top"><div class="section-heading left"><span class="eyebrow">LAYANAN KAMI</span><h2>Beragam kebutuhan.<br>Satu komitmen: <em>sepenuh hati.</em></h2><p>Dari pendampingan sehari-hari hingga perawatan khusus di rumah.</p></div><a href="/layanan" class="btn btn-light">Semua Layanan ${icon('arrow')}</a></div><div class="grid-3">${[SERVICES[1],SERVICES[2],SERVICES[3],SERVICES[0],SERVICES[5],SERVICES[8]].map(serviceCard).join('')}</div><div class="service-footer">Belum yakin layanan yang Anda butuhkan?<a class="text-link" data-wa href="${wa}" target="_blank" rel="noopener">Mari konsultasi ${icon('arrow')}</a></div></div></section>
 <section class="section container">${heading('MUDAH, DARI LANGKAH PERTAMA','Lebih dekat dengan<br><em>perawatan yang tepat.</em>')}<div class="steps">${[['Ceritakan kebutuhan','Isi assessment singkat sesuai kondisi dan kebutuhan keluarga.'],['Konsultasi bersama','Kirim ringkasan ke WhatsApp dan diskusikan dengan tim kami.'],['Tentukan layanan','Konfirmasi tenaga, jadwal, serta biaya yang sesuai.'],['Kami hadir untuk Anda','Pendampingan di rumah sesuai layanan yang disepakati.']].map(([t,d],i)=>`<div><div class="step-number"><span>0${i+1}</span></div><h3>${t}</h3><p>${d}</p></div>`).join('')}</div></section>
 <section class="container">${cta()}</section><section class="section container">${about()}</section>
 <section class="section soft"><div class="container">${heading('CERITA KELUARGA SA3','Kepercayaan yang tumbuh<br>dari <em>kepedulian.</em>','Pengalaman keluarga yang telah menggunakan layanan SA3 Home Care.')}<div class="grid-3">${[['DN','Dodi Nugraha','Perawatnya telaten dan sabar, serta memahami kebutuhan perawatan pasien. Keluarga mengapresiasi komitmen tim dalam mendampingi.'],['AY','Amaisa Ymr','Keluarga terbantu ketika membutuhkan kunjungan dokter dengan cepat. Dokter datang dan menanggapi kebutuhan dengan baik.'],['GS','Dr. Guntur S Simboro','Tanggapan tim cepat, dengan masukan yang membantu. Perawat yang mendampingi dinilai profesional dan baik.']].map(([a,n,q])=>`<article class="testimonial"><div class="quote-mark">“</div><blockquote>${q}</blockquote><div class="person"><span class="avatar">${a}</span><div><strong>${n}</strong><small>Keluarga pengguna layanan SA3</small></div></div></article>`).join('')}</div><p class="small muted" style="text-align:center;margin-top:22px">Diringkas dari testimoni pada <a class="text-link" href="https://jasaperawatbandung.com/" target="_blank" rel="noopener">website SA3 Home Care</a>.</p></div></section>
 <section class="section container"><div class="coverage"><div><span class="eyebrow">AREA PELAYANAN</span><h2>Dekat dengan keluarga,<br><em>di berbagai kota.</em></h2><p>Dari Bandung, jaringan mitra kami menjangkau berbagai wilayah. Hubungi kami untuk memastikan ketersediaan layanan di area Anda.</p><div class="area-tags">${['Bandung','Jabodetabek','Lampung','Jawa Barat','Jawa Timur','Bali'].map(x=>`<span>${x}</span>`).join('')}</div><a class="text-link" href="/kontak">Cek jangkauan layanan ${icon('arrow')}</a></div><div class="coverage-art">${icon('pin')}<div class="island">Dari Bandung,<br>untuk keluarga<br>Indonesia.</div><small>SUMATERA · JAWA · BALI</small></div></div></section>
 <section class="section soft"><div class="container"><div class="section-top"><div class="section-heading left"><span class="eyebrow">RUANG INFORMASI</span><h2>Bekal kecil untuk<br><em>merawat lebih baik.</em></h2></div><a class="text-link" href="/blog">Semua Artikel ${icon('arrow')}</a></div><div class="grid-3">${blogCards()}</div></div></section>`;}
function pageHero(label,title,text){return `<section class="page-hero"><span class="eyebrow">${label}</span><h1>${title}</h1><p>${text}</p></section>`;}
function aboutPage(){return `${pageHero('CERITA KAMI','Hadir dengan ilmu.<br>Merawat dengan <em>hati.</em>','Kami Ada Sepenuh Hati Untuk Anda')}<section class="section container">${about()}</section><section class="section soft"><div class="container">${heading('NILAI YANG MENYATUKAN KAMI','Silih Asih. Silih Asah. <em>Silih Asuh.</em>')}<div class="grid-3">${[['Silih Asih','Saling mengasihi','Menghadirkan perhatian tulus dan menghargai setiap pribadi.'],['Silih Asah','Saling berbagi pengetahuan','Membantu keluarga memahami kebutuhan pendampingan melalui komunikasi yang jelas.'],['Silih Asuh','Saling menjaga','Membangun dukungan berkesinambungan bersama keluarga dan tenaga kesehatan.']].map(([t,s,d])=>`<div class="card"><div class="icon-box">${icon('heart')}</div><h3>${t}</h3><span class="eyebrow">${s}</span><p>${d}</p></div>`).join('')}</div></div></section><section class="section container"><div class="grid-2"><div class="card content-copy"><span class="eyebrow">VISI KAMI</span><h2>Mitra perawatan<br>yang Anda percaya.</h2><p>Menjadi platform layanan home care terpercaya di Indonesia, dengan kualitas, profesionalisme, dan empati bagi pasien serta keluarga.</p></div><div class="card content-copy"><span class="eyebrow">MISI KAMI</span><h2>Pelayanan yang<br>berpusat pada manusia.</h2><p>Menghubungkan keluarga dengan mitra tenaga kesehatan, memberikan edukasi yang mudah dipahami, serta mendampingi kebutuhan perawatan secara personal.</p><p>Tindakan medis dan keperawatan dilakukan oleh mitra tenaga kesehatan sesuai kompetensi dan izin yang berlaku.</p></div></div></section><section class="container section">${cta()}</section>`;}
function servicesPage(){return `${pageHero('LAYANAN SA3 HOME CARE','Perawatan yang mengikuti<br><em>kebutuhan keluarga.</em>','Diskusikan layanan, durasi, dan jadwal yang tepat bersama tim kami.')}<section class="section container"><label class="form-field service-search">Cari layanan<input type="search" id="service-search" placeholder="Pendampingan lansia, fisioterapi, dokter…"></label><div class="grid-3" id="service-list">${SERVICES.map(serviceCard).join('')}</div><p id="service-empty" class="empty-state" hidden>Layanan tidak ditemukan. Coba kata kunci lain.</p></section><section class="container section">${cta()}</section>`;}
function contactPage(){return `${pageHero('HUBUNGI KAMI','Kami siap <em>mendengarkan.</em>','Ceritakan kebutuhan keluarga, tanyakan jangkauan layanan, atau jadwalkan konsultasi awal.')}<section class="section container"><div class="grid-3"><div class="card contact-card"><div class="icon-box">${icon('chat')}</div><h3>Mulai percakapan</h3><p>Diskusikan layanan dan ketersediaan tenaga bersama tim SA3.</p><a class="btn" data-wa href="${wa}" target="_blank" rel="noopener">${icon('whatsapp','on-dark')} WhatsApp ${icon('arrow')}</a><p class="small" style="margin-top:15px">0823 1919 9534<br>0895 3254 04906</p></div><div class="card contact-card"><div class="icon-box">${icon('pin')}</div><h3>Temui kami di Bandung</h3><p>Jl. Lodaya No.65, Malabar<br>Kota Bandung, Jawa Barat</p><a class="text-link" href="https://www.google.com/maps/search/?api=1&query=Jl.+Lodaya+No.65+Malabar+Bandung" target="_blank" rel="noopener">Lihat lokasi ${icon('arrow')}</a></div><div class="card contact-card"><div class="icon-box">${icon('mail')}</div><h3>Kirim email</h3><p>Untuk informasi umum dan kebutuhan kerja sama.</p><a class="text-link" href="mailto:homecaresa3@gmail.com">homecaresa3@gmail.com ${icon('arrow')}</a></div></div><div style="margin-top:40px">${cta()}</div></section>`;}
function blogPage(){const id=new URLSearchParams(location.search).get('artikel');if(id){const a=articles.find(x=>x.id===id);if(!a)return `<section class="section container empty-state"><h1>Artikel tidak ditemukan</h1><a class="btn" href="/blog">Kembali ke artikel</a></section>`;document.title=`${a.title} | SA3 Home Care`;return `<section class="section container"><article class="article"><a class="text-link" href="/blog">← Semua artikel</a><p class="eyebrow">${a.category} · ARTIKEL PROTOTYPE</p><h1>${a.title}</h1><img src="/assets/images/${a.image}" width="800" height="340" alt="Pendampingan keluarga di rumah">${a.paragraphs.map(p=>`<p>${p}</p>`).join('')}<a class="btn" href="/assessment">Ceritakan kebutuhan Anda ${icon('arrow')}</a></article></section>`;}return `${pageHero('RUANG INFORMASI','Mendampingi keluarga,<br><em>berbagi pengetahuan.</em>','Panduan sederhana untuk memahami layanan dan mempersiapkan pendampingan di rumah.')}<section class="section container"><div class="grid-3">${blogCards()}</div><p class="small muted" style="margin-top:25px">Artikel informasi layanan untuk prototype; bukan panduan diagnosis atau pengobatan.</p></section>`;}
const pages={index:home,tentang:aboutPage,layanan:servicesPage,kontak:contactPage,blog:blogPage};
if(pages[page])$('#main-content').innerHTML=pages[page]();
if(page==='layanan')$('#service-search').addEventListener('input',e=>{const query=e.target.value.trim().toLowerCase();const results=SERVICES.filter(s=>(s.name+' '+s.desc).toLowerCase().includes(query));$('#service-list').innerHTML=results.map(serviceCard).join('');$('#service-empty').hidden=results.length>0;window.AOS?.refresh();});
if(window.AOS && !matchMedia('(prefers-reduced-motion: reduce)').matches){window.AOS.init({duration:550,once:true,offset:35,easing:'ease-out-cubic'});document.documentElement.classList.add('aos-ready');}
adminNumber().then(n=>{document.querySelectorAll('[data-wa]').forEach(a=>a.href=buildWhatsAppUrl(n,'Halo SA3 Home Care, saya ingin berkonsultasi mengenai layanan home care.'));}).catch(()=>{});
